version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.9.0-browsers

    steps:
      - checkout

      - run: sudo npm i -g firebase-tools

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - run:
          name: deploy to firebase hosting
          command:
              if ["$CIRCLE_BRANCH" == "master"];
              then
                npm run firebse-hosting-deploy
              fi
