version: 2
jobs:
  build:
    branches:
      ignore:
        - master
    docker:
      - image: circleci/node:11.9.0

    steps:
      - checkout

      - run: sudo npm i -g firebase-tools

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          
      - run: npm run build
      - run: npm run firebse-hosting-deploy 
